apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: aliabodaraa/auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TEMP_2FA_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: temp-2fa-token-secret
                  key: TEMP_2FA_TOKEN_SECRET
            - name: EMAIL_FROM
              value: "abodaraaali50@gmail.com"
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: email-pass-secret
                  key: EMAIL_PASS
            - name: FRONTEND_BASE_URL
              value: "https://ticketing.dev/auth/verification-redirection"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
